# Generated by Django 4.1.7 on 2023-04-28 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_friends_delete_friendship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friends",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="friends",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="follower", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
