# Generated by Django 4.1.7 on 2023-05-07 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_friends_follower_alter_friends_following"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Friends",
            new_name="FriendShip",
        ),
    ]
